name: Code Style

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'

jobs:
  Pint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Launch Pint inspection
        run: vendor/bin/pint --test
